name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "09 07 * * *" # Daily at 12:09 PM PDT, 11:09 PM PST.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
      - run: pnpm i
      - run: pnpm run build
      - name: Setup Clasp Auth
        run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
      - run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
